### ISSUE TITLE
Moonpay: Add ability to set custom redirectURL on complete

### ISSUE THREAD

**Issue by ok300** [breez/breez-sdk#911] opened 2024-04-03 07:04 UTC
Allow the caller to set a custom ... , which can point to their own custom landing page or in-app view.

https://github.com/breez/breez-sdk/blob/e541135b0f1fa90f964829444cb34d53251660e5/libs/sdk-core/src/moonpay.rs#L24

**Comment by roeierez** [comment] 2024-04-07 11:10
duplicate of https://github.com/breez/breez-sdk/issues/912

**Closed by roeierez** 2024-04-07 11:10 UTC
