### ISSUE TITLE
Node refunded balance but breez thinks Swap is in progress. Cannot fund lightning because of it.

### ISSUE THREAD

**Issue by sagarsubedi** [breez/breez-sdk#715] opened 2024-01-09 18:00 UTC
### Scenario
User had $100
The user tried to fund the Lightning network with $50 via an on-chain transaction.
The transaction took a very long time (more than 1month) and it was never mined, so it was returned and the on-chain balance was reset back to the amount prior to funding. (So user now has $100 again, without us executing any refunds.)
The user tried to fund the Lightning network again via an on-chain transaction, but it failed.
After debugging, we found that Breeze SDK still says there is a “Swap in progress”, indicating that funding is still processed.

So, because of this user cannot fund their lightning again since breez says there is a swap already in progress.

**Comment by ok300** [comment] 2024-01-09 19:06
Thanks for the detailed report @sagarsubedi . Here's some background and how to fix the problem:

Once a swap is started, the sent sats can follow one of two paths:

- they can be received as LN balance,
- they can be refunded from the swap address. This is triggered via an SDK `refund` call.

In your scenario, the user is in the second branch. Depending on which wallet and mempool they used to send the onchain sats, the initial transaction may not be shown anymore because it wasn't mined for a long time.

However, independent of that, the original transaction may still be present in some mempools, and technically it could still end up being mined sooner or later.

Therefore, the only way to reliably and safely cancel the swap is by issung a `refund` from the SDK. We have detailed infos on how to do it [in our docs](https://sdk-doc.breez.technology/guide/receive_onchain.html#refund-a-swap).

Can you please coordinate with your user to `refund` this ongoing swap? That should fix the issue.

**Comment by sagarsubedi** [comment] 2024-01-09 19:10
Just an FYI, the user is using a wallet backed by `bdk_flutter` and following node was used: `ssl://electrum.acinq.co:50002` by the wallet. Okay I will be able to coordinate with the user tomorrow and run some manual code. I will try refund again and  update this ticket with what happens. Thanks for the suggestions.

**Comment by sagarsubedi** [comment] 2024-01-10 18:27
I tried executing the `refund()` but got this error:

> FfiException (FfiException(RESULT_ERROR, must have at least one input, null))

For the input I called `inProgressSwap()` and used the `response.bitcoinAddress` as `fromAddress` and user's btc address for `toAddress`.
FYI: `listRefundables()` returns empty list, so this does not look like it can be refunded.
@ok300 Any more info you need from me?

**Comment by ok300** [comment] 2024-01-10 21:51
It's indeed a weird situation.

Can you please post here (or send me in a DM) the full response of `inProgressSwap()`?

**Comment by ok300** [comment] 2024-01-11 07:14
Can you please use RBF to bump the fees on the original swap transaction? The one that wasn't confirmed for >1 month?

Once confirmed, can either successfully complete, or will be refundable.

**Comment by roeierez** [comment] 2024-01-30 10:46
Will be fixed by https://github.com/breez/breez-sdk/issues/726

**Closed** 2024-02-12 19:36 UTC
